---
dependencies:
  - role: jdauphant.ssl-certs
  - role: jdauphant.nginx
    nginx_configs:
      ssl:
        - ssl_certificate_key {{ssl_certs_privkey_path}}
        - ssl_certificate     {{ssl_certs_cert_path}}
      invalid_headers:
        - ignore_invalid_headers off
    nginx_sites:
      nuxeo:
        # TODO external URL (here https://nuxeo.local) should be a
        # variable for the https role
        - listen 443 ssl
        - location / {
            proxy_set_header nuxeo-virtual-host https://nuxeo.local/;
            proxy_pass     http://localhost:8080;
            proxy_redirect http://localhost:8080 https://nuxeo.local;
          }
